In [50]:
#import library
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
from sklearn.preprocessing import LabelEncoder

In [51]:
#upload data ke google colab
from google.colab import files
uploaded = files.upload()

Saving Mall_Customers.csv to Mall_Customers (1).csv


In [3]:
#load dataset
df = pd.read_csv("Mall_Customers.csv")
df

CustomerID  Gender  Age  Annual Income (k$)  Spending Score (1-100)  \
0             1    Male   19                  15                      39   
1             2    Male   21                  15                      81   
2             3  Female   20                  16                       6   
3             4  Female   23                  16                      77   
4             5  Female   31                  17                      40   
..          ...     ...  ...                 ...                     ...   
195         196  Female   35                 120                      79   
196         197  Female   45                 126                      28   
197         198    Male   32                 126                      74   
198         199    Male   32                 137                      18   
199         200    Male   30                 137                      83   

    Potential Buy  
0          Sedang  
1          Tinggi  
2          Rendah  
3          Tinggi  
4          Sedang  
..            ...  
195        Tinggi  
196        Sedang  
197        Tinggi  
198        Rendah  
199        Tinggi  

[200 rows x 6 columns]

In [52]:
#data preparation
df.info()
df.isnull().sum()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 200 entries, 0 to 199
Data columns (total 6 columns):
 #   Column                  Non-Null Count  Dtype 
---  ------                  --------------  ----- 
 0   CustomerID              200 non-null    int64 
 1   Gender                  200 non-null    int64 
 2   Age                     200 non-null    int64 
 3   Annual Income (k$)      200 non-null    int64 
 4   Spending Score (1-100)  200 non-null    int64 
 5   Potential Buy           200 non-null    object
dtypes: int64(5), object(1)
memory usage: 9.5+ KB


CustomerID                0
Gender                    0
Age                       0
Annual Income (k$)        0
Spending Score (1-100)    0
Potential Buy             0
dtype: int64

In [7]:
#konversi variabel kategorikal ke numerik
label_encoder = LabelEncoder()
df['Gender'] = label_encoder.fit_transform(df['Gender'])
df

CustomerID  Gender  Age  Annual Income (k$)  Spending Score (1-100)  \
0             1       1   19                  15                      39   
1             2       1   21                  15                      81   
2             3       0   20                  16                       6   
3             4       0   23                  16                      77   
4             5       0   31                  17                      40   
..          ...     ...  ...                 ...                     ...   
195         196       0   35                 120                      79   
196         197       0   45                 126                      28   
197         198       1   32                 126                      74   
198         199       1   32                 137                      18   
199         200       1   30                 137                      83   

    Potential Buy  
0          Sedang  
1          Tinggi  
2          Rendah  
3          Tinggi  
4          Sedang  
..            ...  
195        Tinggi  
196        Sedang  
197        Tinggi  
198        Rendah  
199        Tinggi  

[200 rows x 6 columns]

In [40]:
#split dataset
X = df.drop('Potential Buy', axis=1)
y = df['Potential Buy']
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [41]:
#membangun model
model = RandomForestClassifier()
model.fit(X_train, y_train)

RandomForestClassifier()

In [42]:
#K-Fold Cross Validation
from sklearn.model_selection import cross_val_score, KFold

kfold = KFold(n_splits=5, shuffle=True, random_state=42)
results = cross_val_score(model, X, y, cv=kfold)

In [43]:
results

array([0.75, 0.8 , 0.65, 0.75, 0.75])

In [44]:
#menampilkan hasil validasi
print(f"Accuracy: {results.mean()} (std: {results.std})")

Accuracy: 0.74 (std: <built-in method std of numpy.ndarray object at 0x780ddb81f3f0>)


In [45]:
#melakukan prediksi pada data testing
y_pred = model.predict(X_test)

In [46]:
#evaluasi model
accuracy = accuracy_score(y_test, y_pred)
conf_matrix = confusion_matrix(y_test, y_pred)
classification_rep = classification_report(y_test, y_pred)

In [47]:
#menampilkan hasil evaluasi
print(f"Accuracy: {accuracy}")
print("Confusion Matrix:")
print(conf_matrix)
print("Classification Report:")
print(classification_rep)


Accuracy: 0.75
Confusion Matrix:
[[ 9  0  0]
 [ 2  9  4]
 [ 1  3 12]]
Classification Report:
              precision    recall  f1-score   support

      Rendah       0.75      1.00      0.86         9
      Sedang       0.75      0.60      0.67        15
      Tinggi       0.75      0.75      0.75        16

    accuracy                           0.75        40
   macro avg       0.75      0.78      0.76        40
weighted avg       0.75      0.75      0.74        40

